simpler approach to updating submodules

diff --git a/scripts/common/get b/scripts/common/get
--- a/scripts/common/get
+++ b/scripts/common/get
@@ -14,13 +14,13 @@ do
     fi
 
     (cd "$dir"; 
-        if [ -d .git ]; then git pull -q || echo "$dir": failed; fi
-        if [ -f .gitmodules ]; then git submodule update --init --recursive; fi
-        # unfortunately some repos use 'master' and some use 'main'
-        if [ -f .gitmodules ]; then git submodule foreach --recursive 'git checkout master'; fi
-        if [ -f .gitmodules ]; then git submodule foreach --recursive 'git checkout main'; fi
         if [ -d .svn ]; then svn update; fi
         if [ -d CVS ]; then cvs update; fi
+        if [ -d .git ]; then git pull -q || echo "$dir": failed; fi
+        if [ -f .gitmodules ]; then
+            # recursively update submodules
+            git submodule update --init --rebase --recursive;
+        fi
     )
     sleep 1  # for some reason, things lock up if I move too fast
 done
